image: pandoc/latex:latest

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          script:
            - pandoc --to=beamer --from=markdown src/bap-presentation.md -o build/bap-presentation.pdf 
          artifacts:
            - build/bap-presentation.pdf
